### ISSUE TITLE
numCandidateEnhGene and numTSSEnhGene features not computed for promoter elements

### ISSUE THREAD

**Issue by argschwind** [EngreitzLab/ENCODE_rE2G#58]
The numCandidateEnhGene and numTSSEnhGene features are not computed for candidate elements that are classified as promoters. This leads to the feature values for E-G pairs involving promoters being 0 (fill value), regardless of how many other elements of TSS are between the element and gene.

This shouldn't have an impact on the thresholded predictions, as we're filtering out any promoters except for self-promoters.

**Comment by mayasheth** [comment]
This has been addressed and updated in the dev branch.
